# Generated by Django 4.1.7 on 2023-02-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='static/images'),
        ),
    ]
